#!/bin/bash
set -e

# Variables
POSTGRES_USER=Chad
POSTGRES_PASSWORD=Giga
POSTGRES_DB=postgres

# Create user and database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER $POSTGRES_USER WITH PASSWORD '$POSTGRES_PASSWORD';
    CREATE DATABASE $POSTGRES_DB;
    GRANT ALL PRIVILEGES ON DATABASE $POSTGRES_DB TO $POSTGRES_USER;
    CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
EOSQL

